--- 
abstract: use TT to interpolate lexical variables
author: 
  - Jonathan Rockway C<< jrockway@cpan.org >>
build_requires: 
  Test::More: 0
  Test::TableDriven: 0
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: String-TT
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  List::Util: 0
  PadWalker: 0
  Sub::Exporter: 0
  Template: 0
version: 0.02
